### ISSUE TITLE
Definir novo layout para o site

### ISSUE THREAD

**Issue by fabiocerqueira** [pugce/pycon-ce#1]
Sugestão de template: http://pug-se.github.io/pythonday/

**Comment by rafael-neri** [comment]
@fabiocerqueira, aqui outro template bacana: http://braziljs.github.io/conf-boilerplate/

**Comment by fabiocerqueira** [comment]
Acho que o layout poderia ter uma parte institucional para explicar um pouco sobre o grupo, ter os links da comunidade e espaço para divulgação dos nossos parceiros.
